# Generated by Django 5.1.4 on 2024-12-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('basic_medical_history', models.TextField(blank=True, null=True)),
                ('verified_by_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
